name: Auto-deploy-to-dreamhost-development

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: 
      - main

jobs:
  deploy_to_dreamhost_sftp:
    runs-on: ubuntu-latest
    name: Deploy To Dreamhost sFTP
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy file
        uses: whattheearl/sftp-deploy-action@v2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './*'
          remote_path: '/home/mairaj_wp_wpvisions/mairaj.wp.wpvisions.com/wp-content/plugins/mairaj-plugin'
