name: Auto-deploy-to-dreamhost-development

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Plugin Folder to DreamHost
        run: scp -r ./mairaj-plugin mairaj_wp_wpvisions@iad1-shared-e1-11.dreamhost.com:~/mairaj.wp.wpvisions.com/wp-content/plugins/
